parameters:
    env(REDIS_PORT): '6379'
    env(REDIS_TIMEOUT): '0'
    env(REDIS_PERSISTENT_ID): null
    env(REDIS_RETRY_INTERVAL): '0'
    env(REDIS_READ_TIMEOUT): '0'

services:
    TohidHabiby\RedisIntendedJsonSearch\Builder\BuilderInterface:
        class: TohidHabiby\RedisIntendedJsonSearch\Builder\Builder
        autowire: true
        public: true

    Redis:
        class: Redis

    TohidHabiby\RedisIntendedJsonSearch\Builder\RedisConnection:
        autowire: true
        public: true
        arguments:
            $host: '%env(REDIS_HOST)%'
            $port: '%env(REDIS_PORT)%'
            $timeout: '%env(REDIS_TIMEOUT)%'
            $persistentId: '%env(REDIS_PERSISTENT_ID)%'
            $retryInterval: '%env(REDIS_RETRY_INTERVAL)%'
            $readTimeout: '%env(REDIS_READ_TIMEOUT)%'
